### ISSUE TITLE
Main tarsnap class does not "contain" tarsnap::install and tarsnap::config subclasses

### ISSUE THREAD

**Issue by cpick** [Brainsware/puppet-tarsnap#9]
The main tarsnap class declares tarsnap::install and tarsnap::config but it doesn't ["contain"](http://docs.puppetlabs.com/puppet/3.8/reference/lang_containment.html) them.  As a result users of the tarsnap class cannot effectively include it in dependencies.

For example, I noticed this when I tried to install tarsnap from the PPA:

```
apt::ppa { 'ppa:tarsnap/lts': }
class { 'tarsnap': require => Exec['apt_update'], }
```

If the sub-classes were contained, the above "require" attribute would ensure that the PPA was installed and that apt had been updated before the tarsnap module attempted to install the tarsnap package.  As it's currently implemented my installation failed because the tarsnap package could not be found.

**Comment by igalic** [comment]
@cpick do you think we could use [`contain`](http://docs.puppetlabs.com/references/3.7.latest/function.html#contain)?

**Comment by cpick** [comment]
Yes, I believe that that's exactly the right way to solve the problem.  The only downside to that solution is that the 'contain' keyword didn't exist before Puppet 3.4.0 and Puppet Enterprise 3.2.  That's no problem for me, I use modern Puppet, but if compatibility with older versions of Puppet is required the [anchor pattern](http://docs.puppetlabs.com/puppet/3.8/reference/lang_containment.html#anchor-pattern-containment-for-compatibility-with-puppet--340) can be used.

**Comment by igalic** [comment]
let's give it a day or so to let opinions from other people trickle in, and if noone disagrees, we should fix it at 3.6.x (which is when contain was actually fixed to work properly ;)

**Comment by igalic** [comment]
i'm working on a new release…
…a release with #6/#8 .. so… uhm… any opinions on contain?

**Comment by igalic** [comment]
now that in Brainsware-tarsnap 2.0.1, we're puppet4 only, we *do* just use contain.
